trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ls -la
    npm install
  displayName: 'Install dependencies'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykforNodejs'
    testType: 'app'
    targetFile: 'package.json'
    severityThreshold: 'critical'
    monitorWhen: 'always'
    failOnIssues: false
    # projectName: 'juiceShop'
  displayName: 'Scan the BookieApp'
